include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - build
  - scan

build:ubuntu:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  variables:
    DOCKER_BUILDKIT: 1
  script:
    - cd Ubuntu
    - VERSION=$(wget -qO- https://github.com/keybase/bot-sshca/releases | grep -oP '(?<=releases\/tag\/)(.*?)(?=\">)' | awk 'NR==1{print $1}')
    - VERSION_SHORT=$(echo ${VERSION} | cut -d'-' -f 1)
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}" "latest,${VERSION}")
    - TAG_LIST="$(helper "jitesoft/keybase-sshca" "latest,${VERSION},${VERSION_SHORT}") ${TAG_LIST}"
    - docker buildx build --platform "linux/arm64,linux/amd64" --build-arg VERSION="${VERSION}" --progress plain --push ${TAG_LIST} .
    - docker pull ${CI_REGISTRY_IMAGE}:latest
    - helper multitag ${CI_REGISTRY_IMAGE}:latest quay.io/jitesoft/keybase-sshca:latest quay.io/jitesoft/keybase-sshca:${VERSION} quay.io/jitesoft/keybase-sshca:${VERSION_SHORT}
    - helper multipush quay.io/jitesoft/keybase-sshca:latest quay.io/jitesoft/keybase-sshca:${VERSION} quay.io/jitesoft/keybase-sshca:${VERSION_SHORT}
  tags: [ jitesoft, protected, buildx ]

build:alpine:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  variables:
    DOCKER_BUILDKIT: 1
  script:
    - cd Alpine
    - VERSION=$(wget -qO- https://github.com/keybase/bot-sshca/releases | grep -oP '(?<=releases\/tag\/)(.*?)(?=\">)' | awk 'NR==1{print $1}')
    - VERSION_SHORT=$(echo ${VERSION} | cut -d'-' -f 1)
    - TAG_LIST=$(helper "${CI_REGISTRY_IMAGE}/alpine" "latest,${VERSION}")
    - TAG_LIST="$(helper "jitesoft/keybase-sshca" "latest-alpine,${VERSION}-alpine,${VERSION_SHORT}-alpine") ${TAG_LIST}"
    - docker buildx build --platform "linux/arm64,linux/amd64" --build-arg VERSION="${VERSION}" --progress plain --push ${TAG_LIST} .
    - docker pull ${CI_REGISTRY_IMAGE}/alpine:latest
    - helper multitag ${CI_REGISTRY_IMAGE}/alpine:latest quay.io/jitesoft/keybase-sshca:latest-alpine quay.io/jitesoft/keybase-sshca:${VERSION}-alpine quay.io/jitesoft/keybase-sshca:${VERSION_SHORT}-alpine
    - helper multipush quay.io/jitesoft/keybase-sshca:latest-alpine quay.io/jitesoft/keybase-sshca:${VERSION}-alpine quay.io/jitesoft/keybase-sshca:${VERSION_SHORT}-alpine
  tags: [ jitesoft, protected, buildx ]

scan:ubuntu:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"

scan:alpine:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/alpine:latest"
